#!/usr/bin/env python3
"""
Generate an Ed25519 keypair for mission signing.

Usage:
  python3 Tools/generate_keypair.py

Outputs:
  Tools/mission_privkey.pem  -- private key (KEEP SECRET, never commit)
  Tools/mission_pubkey.h     -- public key as C array for firmware

After generating, copy the array from mission_pubkey.h into
MISSION_SIGNING_PUBLIC_KEY in missionHashCheck.cpp and rebuild PX4.
"""

import os
import sys

try:
    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives.serialization import (
        Encoding, PrivateFormat, PublicFormat, NoEncryption)
except ImportError:
    print("ERROR: 'cryptography' package not installed.")
    print("       pip3 install cryptography")
    sys.exit(1)

TOOLS_DIR = os.path.dirname(os.path.abspath(__file__))


def main():
    key = Ed25519PrivateKey.generate()
    pub_raw = key.public_key().public_bytes(Encoding.Raw, PublicFormat.Raw)
    priv_pem = key.private_bytes(Encoding.PEM, PrivateFormat.PKCS8, NoEncryption())

    priv_path = os.path.join(TOOLS_DIR, "mission_privkey.pem")
    pub_path  = os.path.join(TOOLS_DIR, "mission_pubkey.h")

    with open(priv_path, "wb") as f:
        f.write(priv_pem)
    os.chmod(priv_path, 0o600)
    print(f"Wrote private key : {priv_path}  (chmod 600 — keep secret)")

    arr = ", ".join(f"0x{b:02x}" for b in pub_raw)
    header = (
        "#pragma once\n"
        "// Ed25519 public key for mission signature verification.\n"
        "// Generated by Tools/generate_keypair.py — regenerate for production.\n"
        "// Copy this array into MISSION_SIGNING_PUBLIC_KEY in missionHashCheck.cpp\n"
        "// and rebuild PX4.\n"
        "static const uint8_t MISSION_SIGNING_PUBLIC_KEY[32] = {\n"
        f"\t{arr}\n"
        "};\n"
    )

    with open(pub_path, "w") as f:
        f.write(header)
    print(f"Wrote public key  : {pub_path}")
    print()
    print("Next steps:")
    print(f"  1. Add Tools/mission_privkey.pem to .gitignore (never commit the private key)")
    print(f"  2. Open {pub_path} and copy the array into")
    print( "     MISSION_SIGNING_PUBLIC_KEY in")
    print( "     src/modules/commander/HealthAndArmingChecks/checks/missionHashCheck.cpp")
    print( "  3. Rebuild: make px4_sitl gz_x500")
    print( "  4. Sign missions: python3 Tools/mission_sign.py <plan.plan>")


if __name__ == "__main__":
    main()
